### ISSUE TITLE
Quality checks in Input.makeStars() 

### ISSUE THREAD

**Issue by eacharles** [rmjarvis/Piff#101]
In Ares's development branch he has implemented some quality checks in the Input.makeStars() function().   You can see those in the eac-dev branch.

I'm not sure this is actually how we want to handle applying quality cuts to the input star list.  Perhaps we could agree on a model from how that should be done.

**Comment by rmjarvis** [comment]
There are a few options currently that the user can select to cut things from the input:
```
satur
min_snr
use_partial
hsm_size_reject
```
I don't mind adding more, but (a) the default should be not to do the rejection (so default = None presumably), and (b) definitely don't start the parameter name with an underscore.

Comments about the ones that are there:
* _cutoff_deformed_level: I still don't understand why this is necessary.  Seems like `use_partial=False` should do what you need here.
* _cutoff_nuisance_level: This seems ok, although I suspect the hsm_size_reject probably gets you want you need.  I'd suggest a better name though, like `max_edge_flux` or similar.
* _cutoff_maxed_level: Also fine.  Suggest calling it `max_mask_frac` or `max_mask_pixels`.  I would think fraction is broadly more useful, but if you want to keep it as literal number of pixels, that's ok too.

**Comment by rmjarvis** [comment]
> I would think fraction is broadly more useful, but if you want to keep it as literal number of pixels, that's ok too.

Or it occurs to me that we could have it work the same way the Outliers max_remove works.  Namely, if it is >0 but <1, then interpret it as a fraction of the total.  If it is >=1 then interpret it as an absolute number.

**Comment by areshernandez** [comment]
I can't remember why, but my code crashed whenever I attempted to name them without the underscore in the front (I think there may have been some rogue if statement somewhere that I didn't know how to handle at the time).

As far as _cutoff_deformed_level is concerned, this was because of some unit test that was crashing specifically because of a couple of bad stars like this. I can't remember which unit test it was, so I'd rather keep that at least until I've fixed the current problems with the unit tests that are there right now.

**Comment by eacharles** [comment]
One issue here is that it looks like Ares had implemented this in the Input.makeStars() level but the other selections are made in the Input._makeStarsFromImage().  So, independently of the specific cuts, they should all live in _makeStarsFromImage() so that they can be properly parallelized.

**Comment by eacharles** [comment]
Ok, so cutoff_deformed_level is doing a slightly different thing than use partial in that it is an integer, so you can decide how many pixels loss to tolerate.    Obvious, use_partial=False will remove all stars with any missing pixels.    If Ares is only using cutoff_deformed_level = 1 or 1000 then clearly the two are fully equivalent.   For now I've left this in my test code and changed the name to max_deformation.

**Comment by eacharles** [comment]
I've moved all three tests to Input._makeStarsFromImage().   One thing is that the unit tests don't always play nice with the parallelization, some errors in the _makeStarsFromImage() (Like typos) are failing quietly and just causing all the code to return empty lists. 

A second point is that I had to reimplement the cutoff_nuisance_level cut in terms of an absolute cut rather than a cut on the distribution.   (in makeStars() you have access to all the stars and can compute the median of this quantity, in _makeStarsFromImage() you only have one image, and the code is more efficient if you keep everything in a single loop.   I changed this to cutting of the fraction of flux in the "edges"  and setting it to 0.25 had the same effect as Ares's current settings.   I also changed the name to "max_edge_frac" 

A final point is that the mask used to define the edge pixels for the edge flux compuate can be precomputed instead of being computed in the loop.   If we want to use that cut, I'm happy to write modify the code to do that.

**Comment by eacharles** [comment]
The eac-dev branch has all these changes and passes the unit tests.

**Comment by rmjarvis** [comment]
The parallelization in the input reading can be turned off by setting `input.nproc=1` in the config or constructing `InputFiles(..., nproc=1)`.

**Comment by rmjarvis** [comment]
> use_partial=False will remove all stars with any missing pixels. If Ares is only using cutoff_deformed_level = 1 or 1000 then clearly the two are fully equivalent. For now I've left this in my test code and changed the name to max_deformation.

`use_partial = False` is the default.  

Does Ares do `use_partial=False, max_deformation=N` with N > 1`?  I think that's the only way it would ever be relevant?

**Comment by eacharles** [comment]
I'm not sure what conditions Ares uses for max_deformation.    Setting nproc=1 works in the sense that you at least get a terse warning in the log as to the nature of the exception.  It leaves out the stack trace, but its enough to debug.

**Comment by eacharles** [comment]
Ok.  In the interest of moving along, how about if I put together the code for max_masked_pixels and max_edge_frac (including moving the code that defines the edge pixels outside the star loop) and make a PR for that.   We can come pack to the max_deformation stuff later if Ares needs it.

**Comment by rmjarvis** [comment]
Sounds good.  Also, probably make the default values `None` rather than 1000.  It might be equivalent most of the time in practice, but None more cleanly indicates that no rejection for this item should be done.

**Comment by eacharles** [comment]
This has been merged.   Functionally the filter is very close to what what in the galsimify_optatmo_plus_cleaning branch, but the interface has changed a bit.  The relevant parameters are max_masked_pixels (number of masked pixels above which to skip the star), max_edge_frac (fraction of flux outside the central part of the image above which to skip the star ) and stamp_center_size (radius in pixels to consider as the central part of the stamp for the max_edge_frac) cut.

**Comment by areshernandez** [comment]
I've only ever used max_deformation=1, so this is not a problem.

**Comment by rmjarvis** [comment]
OK.  I'm pretty sure that's equivalent to the existing use_partial=False, so I'd recommend just switching to that.  (Which is the default, in fact.)

**Comment by areshernandez** [comment]
I apologize for not noticing this earlier, but since the default for stamp_center_size is 13 that means 13 was likely found as the good default value for a set of stars with a bigger postage stamp than the usual 19x19 I use. Could you point me to which stars you used to find the default value of 13, so I can find the equivalent default for the typical fits I do with 19x19 stamps?

**Comment by rmjarvis** [comment]
13 is appropriate for the default stamp size of 32 (which has a full "radius" of 16).
Just set something appropriate for your stamp size.  If your full radius is 9.5, probably 7.5 or 8 would be a good choice to leave an edge everywhere, but have it isotropic around the center.
