### ISSUE TITLE
Reading WCS solution of ZTF images

### ISSUE THREAD

**Issue by rgraz** [rmjarvis/Piff#119]
Trying to run Piff on ZTF images, it looks like it doesn't properly read the WCS solution of the header. When using default wcs, the psf results are absurd, and not when I use astropy WCS.

You can download an image here, for example : [sciimg](https://irsa.ipac.caltech.edu/applications/ztf/servlet/Download?file=%24%7Bstage%7D%2Fbid1552817930_irsawebops7_ztf_20180328153495_000567_zg_c01_o_q1_sciimg.fits&return=ztf_20180328153495_000567_zg_c01_o_q1_sciimg.fits&log=true&track=true).

My current turn around to this issue is :

```
config = { 'image_file_name' : 'ztf_20180328153495_000567_zg_c01_o_q1_sciimg.fits', 
'image_hdu' : 0,  
'ra':"TELRA", 
"dec":"TELDEC",
# + Some catalogs config depending on the catalog
}


inputfile = piff.InputFiles( config )
astropy_wcs = astropy.wcs.WCS(header) 
new_wcs = galsim.fitswcs.AstropyWCS(wcs=astropy_wcs)
inputfile.setWCS(config = {'wcs' : new_wcs})
```

**Comment by rmjarvis** [comment]
Fixed in GalSim here: https://github.com/GalSim-developers/GalSim/pull/1101
