### ISSUE TITLE
psf.draw | wcs is not a list for single chip fit

### ISSUE THREAD

**Issue by MickaelRigault** [rmjarvis/Piff#121]
Hello, 

I run piff on a single ZTF image (a "quadrant") and stored the output.piff. 

Then, I loaded piff.PSF reading the output file and try to evaluate the psf. The issue is that the loaded piff.wcs is not a list so the `self.wcs[chipnum]` crashes.

I guess simply having a `np.atleast_1d(wcs)` when setting `psf.wcs` will solve the issue. Or a `np.atleast_1d(wcs)[chipnum]` within this part of the code.

Please find the code example attached. 

![image](https://user-images.githubusercontent.com/7812822/103754609-dc40dc80-500c-11eb-9dea-6afa9ea1839f.png)

**Comment by MickaelRigault** [comment]
I have this patch in my code for now. 
```python
self.set_psf( piff.PSF.read(file_name=psffilename, logger=self.logger) )
# tmp piff patch:
self.psf.wcs = list(np.atleast_1d(self.psf.wcs))
```
That solves the problem.

**Comment by rmjarvis** [comment]
Can you post the output file?  I don't see how the read function can end up with a wcs that isn't a dict.  Also maybe the script that generates it.

**Comment by rmjarvis** [comment]
Also, I see that you are using Piff version 0.4.  Can you upgrade to version 1.0 at least and retry.  It's possible this was a bug that has already been fixed.

**Comment by MickaelRigault** [comment]
I updated the code.

Indeed, now the psf.wcs is a dict. 

Sorry about that....

**Comment by rmjarvis** [comment]
Great.  Glad it was simple.  I don't remember fixing a bug related to that, but there very well could have been something in the past year or so.
