### ISSUE TITLE
Implement outlier rejection

### ISSUE THREAD

**Issue by rmjarvis** [rmjarvis/Piff#13]
We need some machinery to handle finding outliers in the interpolation and removing them (and redoing the interpolation).

In the config structure, I think this can be a parameter within the interp field, but in the code, the functionality will be separate from any particular Interpolation class, working with the residuals between the measurements and the interpolated values.

I volunteer to do this, and I plan to implement a few different options.  This [article](http://www.r-bloggers.com/finding-outliers-in-numerical-data/) has a good discussion of the typical kinds of outlier rejection schemes that are usually employed.  I think we should implement their first three options (based on sigma, median absolute deviation, and quartiles), and probably follow their lead in making the MAD scheme the default.

**Comment by gbernstein** [comment]
There would be a few options to consider about rejecting bad data:

1. As you imply above, reject a star if one or more of its best-fit PSF parameters is an outlier from the interpolated pattern.
2. Reject a star if the PSF, interpolated to its location, yields a poor chi-squared (or, more generally, log likelihood) when fit to the data.
3. Reject a star (or some pixels) if the interpolated PSF is a poor fit to one or more of its pixels.

For the latter two options it might be useful to have the Model be able to return the chisq when the model is applied to some StarData.

**Comment by RobertLuptonTheGood** [comment]
I've written code like this, and it can be surprisingly hard to get it to behave.  If you have only a few stars in some corner of a chip with a significant amount of distortion, it's easy to clip them away with an initial guess.   Maybe you've already got beyond this?

**Comment by rmjarvis** [comment]
Right.  I also have code that did this, and I had to set the outlier threshold pretty high to not throw away real data, since my interpolation couldn't track the data terribly well.  (This was using the BTC camera, where one chip had a significant warp that meant the PSF wasn't all that smooth.)

I also kept track of the bounding polygon of the stars that survived outlier rejection and made that the confidence region for the PSF.  Any galaxy outside that polygon was rejected from my shear catalog, since I considered the PSF there suspect.  That way whenever I did throw out stars in the corners, I at least didn't trust my extrapolation there.

Not sure if we need to be that draconian here, but we'll at least want to make some diagnostics to keep track of where the outliers are, so we can investigate if they are systematically in corners and such.

**Comment by gbernstein** [comment]
After pull of #5, can add a method to the Model class that will identify and mask pixels above some level of residual.  There is already a worst_chisq field being filled out in the StarFit structure during fitting which can be checked to find stars with outlier pixels.  Also should arrange to mask neighbor pixels by some _ngrow_ argument.
