### ISSUE TITLE
coadd_object_id in psf_stars extension is stored as an f8 instead of an i8

### ISSUE THREAD

**Issue by esheldon** [rmjarvis/Piff#141]
COADD_OBJECT_ID    >f8  1698368275.0

**Comment by esheldon** [comment]
chipnum is also float rather than int

**Comment by esheldon** [comment]
These also should be int GAIA_SOURCE_ID, VHS_SOURCEID, FLAG_COLOR, is_reserve

**Comment by rmjarvis** [comment]
We currently save all the extra properties we take from the input catalog as float in the output.  The fix would be to keep track of what type they were in the input catalog and copy that to the output.
