### ISSUE TITLE
WCS too complicated for FITS

### ISSUE THREAD

**Issue by gbernstein** [rmjarvis/Piff#19]
We will need to figure out how to incorporate information for WCS that are beyond the ability of the FITS convention to represent (for example tree rings, piecewise models for edge distortions, compound maps).   My C++ astrometry code saves these maps as YAML files but we will have to think whether there is a way to do this short of writing Python code to interpret these YAML files.

**Comment by rmjarvis** [comment]
I think the way forward here is to make a GalSim WCS class that can read your YAML files and do the coordinate transformations.  Then we attach that to the image and everything proceeds normally.  In Piff, we just need a way to tell it to get the WCS from a different place than the FITS header.

**Comment by rmjarvis** [comment]
This was done outside of Piff.  E.g. Gary's `pixmappy` repo has a GalSim WCS that Piff can use (and which we have been using now for a while).  Closing this as there is nothing to do here.
