### ISSUE TITLE
Test failure from numpy bitwise_and

### ISSUE THREAD

**Issue by joezuntz** [rmjarvis/Piff#23]
You may know about this already, but with my version of numpy 1.11.0 I get this test failure.
(I got many other test failures with numpy 1.9 as well; upgrading solved them).

```
======================================================================
ERROR: Test the whole process with a DES CCD.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/jaz/src/piff/tests/test_pixel.py", line 799, in test_des_image
    logger=logger)
  File "/Users/jaz/src/piff/tests/fit_des.py", line 160, in fit_des
    original = stardata_from_fits(ff, xysky, logger=logger)
  File "/Users/jaz/src/piff/tests/fit_des.py", line 77, in stardata_from_fits
    good = np.bitwise_and(msk.array, badmask)==0
TypeError: ufunc 'bitwise_and' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
```

**Comment by rmjarvis** [comment]
I haven't been getting that error on my machine.  

I think likely this was related to an astropy bug fix, which triggered a bug in GalSim, related to unsigned int images.  This was fixed a couple months ago, but we haven't had a new release yet.  Once 1.4 is out (soon, I think!), I think this should be fixed for you.  Or you can use the master branch of GalSim if you want.

In the meanwhile, I think you can change the line to:
```
good = np.bitwise_and(msk.array.astype(np.uint16), badmask)==0
```
and it should work with GalSim 1.3.

**Comment by rmjarvis** [comment]
I went ahead and made that change on master: 2215c19.  Let me know if that works for you.

**Comment by joezuntz** [comment]
You have a typo in that commit - unit16 -> uint16

Joe

**Comment by rmjarvis** [comment]
Oops.  Quite right.  Sorry about that.
