### ISSUE TITLE
Rejected stars in individual PSFs are not propagated to SingleChipPSF

### ISSUE THREAD

**Issue by cpadavis** [rmjarvis/Piff#31]
In SingleChipPSF, we provide a PSF which is deep-copied for each chip. Then we feed it stars based on each chip, which it then fits. Here's the problem:

If your psf has outlier rejection, and stars are actually rejected, this doesn't get propagated back up to SingleChipPSF.stars. That is, len(SingleChipPSF.psf_by_chip[blah].stars) <= len([star for star in SingleChipPSF.stars if star['chipnum'] == blah]). This is bad because our Statistics objects will assess the PSF based on SingleChipPSF, so you're going to get a bunch of outliers that look terrible -- because they were rejected during the fit!

I'm not sure of a clean way to fix this. Maybe some sort of function that just takes all the psf_by_chip's stars and replaces the SingleChipPSF stars attribute? so:

```python
    # in SingleChipPSF.fit(), having run the psf fit
    # update the stars
    self.stars = [star for key in self.psf_by_chip for star in self.psf_by_chip[key].stars]
```

if that's cool with folks, I'll just go ahead and do it, but I wanted to check here in case the current behavior was the expected one

**Comment by rmjarvis** [comment]
Yep, that was an oversight on my part.  Thanks for catching this.  

I think you're fix looks right, although I would probably use `chipnum` rather than `key`, since `psf_by_chip` is indexed by the chipnums.  And probably worth adding a quick unit test for this as well.
