### ISSUE TITLE
DECam pupil plane not sampled well enough.

### ISSUE THREAD

**Issue by rmjarvis** [rmjarvis/Piff#47]
The unit tests currently emit the warning:
```
UserWarning: Input pupil plane image may not be sampled well enough!
Consider increasing sampling by a factor 28.444900, and/or check PhaseScreenPSF outputs for signs of folding in real space.
```
@jmeyers314 @cpadavis I thought we (read Josh) solved this problem through updates to GalSim, but I guess the changes haven't been propagated into Piff yet.  Unfortunately, I don't remember exactly what change needs to be made in the Piff code.  Could one of you take a look and see if we can fix this behavior?

**Comment by cpadavis** [comment]
I don't think my personal computer is on the bleeding latest GalSim master
code, but it currently only gives me that warning for DECam_pupil_128.fits,
and not for DECam_pupil_512.fits. (Former models pupil as 128 x 128 grid,
latter as 512 x 512.) These are for when you feed into Piff the pupil plane
image. The warning is probably actually working as intended; I don't
remember if it was always giving this warning, but I would not be surprised
if it was.

I'm going to dig into whether we can change the parameters to remove the
warning. Alternatively, we could just remove the 128 x 128 version.

**Comment by gogrean** [comment]
I get the warning for both files in Python 3, but only for DECam_pupil_128.fits in Python 2.
