### ISSUE TITLE
python setup.py build fails

### ISSUE THREAD

**Issue by joezuntz** [rmjarvis/Piff#49]
Trying to run ``python setup.py build`` fails with:

    Traceback (most recent call last):
      File "setup.py", line 339, in <module>
        if (dist.script_install_dir not in os.environ['PATH'].split(':') and
    AttributeError: Distribution instance has no attribute 'script_install_dir'

**Comment by rmjarvis** [comment]
What version of setuptools do you have?  Maybe they changed something about this at some point...
```
python -c "import setuptools; print setuptools.__version__"
```

**Comment by rmjarvis** [comment]
FWIW, I have 20.6.7.

**Comment by joezuntz** [comment]
setuptools 23.1.0
and in case useful:
distutils 2.7.12

**Comment by rmjarvis** [comment]
Oh, I figured it out.  This is only for `python setup.py build`.  If you do `python setup.py install` it should work fine.  (And there's not really any reason to do the build version -- install does everything you need.)

**Comment by rmjarvis** [comment]
Fixed on master.  77a4b73
