### ISSUE TITLE
No "config.yaml" example file with latest new features

### ISSUE THREAD

**Issue by areshernandez** [rmjarvis/Piff#62]
To test the new run_data_fits.py script, I sought to try it out on a config.yaml example file. I tried looking for one in the directory /nfs/slac/g/ki/ki19/des/cpd/piff_data/test but there was none. Is there a config.yaml example file saved somewhere where I can test the new features .yaml files now have (such as modifying the nstars parameter)?

**Comment by cpadavis** [comment]
look in /nfs/slac/g/ki/ki19/des/cpd/piff_data/configs

note that the nstars and seed stuff I was talking about in the email only applies for that script file, not for piffify

**Comment by areshernandez** [comment]
There is no piff_data directory inside the /nfs/slac/g/ki/ki19/des/cpd/ directory. Is it possible to modify an old .yaml file to include the new parameters such as seed and nstars to test them?

**Comment by cpadavis** [comment]
sorry: /nfs/slac/g/ki/ki18/cpd/Projects/piff_des/configs

Yes, it just takes regular piff config files. It also doesn't strictly need
the nstars or seed parameters, either.

**Comment by rmjarvis** [comment]
This isn't an issue with Piff.  Either send Chris an email, or comment on the issue where the features you're talking about are being implemented.  It's not appropriate to open a new issue for something like this.
