### ISSUE TITLE
LSSTDESC.Coord easy install sandbox violation

### ISSUE THREAD

**Issue by andrewkbradshaw** [rmjarvis/Piff#71]
Entering the setup command ran into issues with installing LSSTDESC.Coord automatically with easy_install, complaining about a sandbox violation error, first few and last dozen or so lines copied below

`$ sudo python setup.py install`
> Using setuptools version 28.8.0
> Python version =  2.7.12 (default, Dec  4 2017, 14:50:18) 
> [GCC 5.4.0 20160609]
> packages =  ['piff', 'piff.des']
> Checking that GalSim can be imported
> GalSim is version  1.4.2
> Piff version is 0.3

and last dozen lines:

> Installed /usr/local/lib/python2.7/dist-packages/Piff-0.3-py2.7.egg
> Processing dependencies for Piff==0.3
> Searching for LSSTDESC.Coord
> Reading https://pypi.python.org/simple/LSSTDESC.Coord/
> Downloading https://pypi.python.org/packages/98/24/51b5ec9c4480508f786fe3fe09c7b441d79160ce4a879d1ed9977a585946/LSSTDESC.Coord-1.0.5.tar.gz#md5=317f0a789100aaa461d1ea1167ce2a8f
> Best match: LSSTDESC.Coord 1.0.5
> Processing LSSTDESC.Coord-1.0.5.tar.gz
> Writing /tmp/easy_install-sEKLtA/LSSTDESC.Coord-1.0.5/setup.cfg
> Running LSSTDESC.Coord-1.0.5/setup.py -q bdist_egg --dist-dir /tmp/easy_install-sEKLtA/LSSTDESC.Coord-1.0.5/egg-dist-tmp-chpl_K
> Python version =  2.7.12 (default, Dec  4 2017, 14:50:18) 
> [GCC 5.4.0 20160609]
> sources =  ['src/Angle.cpp']
> headers =  ['include/Angle_C.h']
> error: SandboxViolation: symlink('../include/', 'coord/include') {}
> 
> The package setup script has attempted to modify files on your system
> that are not within the EasyInstall build area, and has been aborted.
> 
> This package cannot be safely installed by EasyInstall, and may not
> support alternate installation locations even if you run its setup
> script by hand.  Please inform the package's author and the EasyInstall
> maintainers to find out if a fix or workaround is available.

However, I got around this and successfully installed Piff after:
`$ sudo pip install LSSTDESC.Coord`

**Comment by rmjarvis** [comment]
Thanks for the report Andrew.  I guess the action to take here is just to add to the installation instructions that for the setup.py installation, you should first run 
```
pip install -r requirements.txt
```
since easy_install isn't as reliable as pip in installing requirements.
