### ISSUE TITLE
Make it easier to specify how the PSF profile should be centered on an image

### ISSUE THREAD

**Issue by rmjarvis** [rmjarvis/Piff#73]
Currently `psf.draw(x,y)` centers the PSF profile at the sub-pixel values of the provided x,y positions.

This is sometimes a desirable feature, but not always.  We should make it easier for the user to specify how they want the PSF image centered.  I'm proposing a new `center` keyword argument to the draw command with the following options:
```
center=None   # (default) the current behavior using (x,y) for the sub-pixel position.
center=True     # center the profile at the actual center of the image.
center=pos      # center the profile at some other arbitrary position on the image.
```

**Comment by esheldon** [comment]
works for me

**Comment by RobertLuptonTheGood** [comment]
Why is this needed?  Can't the user just say (int(x), int(y)) to centre in a pixel?  I don't understand the `center=pos` option.  Does it mean calculate the PSF at the specified position, but draw it as if it were at `pos`?

**Comment by rmjarvis** [comment]
FYI, I'll mostly be leveraging the work I did on [this GalSim PR](https://github.com/GalSim-developers/GalSim/pull/1053) where I added a `center` parameter to the `drawImage` command.  This will encompass how the `center=pos` option will work.  The other two options described above will just define two reasonable values for what that pos might be.
