### ISSUE TITLE
Update example des.yaml

### ISSUE THREAD

**Issue by chihway** [rmjarvis/Piff#78]
Two problems I've ran into trying to run the example des.yaml.

1. in the des.yaml, it was complaining not getting "image_file_name" and "cat_file_name". I commented out the "images" and "cats" lines and fed it a specific image and catalog... it also didn't like the 'chipnums' line.

2. in psf.py it seems like the argument "copy_image" is obsolete?
 File "/Users/chihwaychang/anaconda3/envs/galsim/lib/python3.6/site-packages/Piff-0.3-py3.6.egg/piff/psf.py", line 196, in <listcomp>
TypeError: drawStar() got an unexpected keyword argument 'copy_image'

**Comment by rmjarvis** [comment]
Finally done in #118.
