### ISSUE TITLE
Gaussian mixtures model

### ISSUE THREAD

**Issue by rmjarvis** [rmjarvis/Piff#9]
@esheldon suggested adding a Gaussian mixtures model.  Of course, ngmix already does this, so it should be pretty straightforward to write a Model that mostly just calls out to ngmix functionality to do the work.

**Comment by esheldon** [comment]
I didn't suggest mixtures, but when I saw people were wanting to do gaussian/multi-gaussian fits I thought ngmix is a natural choice.

I see gaussian_model.py; Is the idea to replace that?  And add an additional gmix_model.py or something like that?

**Comment by rmjarvis** [comment]
I think we would want an additional model class that does Gaussian Mixtures, not a replacement.  I not exactly sure how the interpolation would go with a gmix model.  Unless the multiple Gaussians are fixed in their relative positions, it might not make much sense to interpolate the parameters between two stars. 

Maybe have a first pass that tries to figure out a good number of Gaussians and their relative positions, and then a second pass that forces that configuration on all the stars?

**Comment by esheldon** [comment]
I agree it is not clear how interpolation would work.  And fixing the relative locations would possibly remove any advantage of  using the mixture model.

**Comment by esheldon** [comment]
For the above reasons, I think we should close this and not bother with the gaussian mixtures.

**Comment by rmjarvis** [comment]
Sure.  If we think of a way to use it, we can certainly reopen or make a new issue at that time.
